import React from 'react';
import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css"
import NextAuthProvider from "@/providers/nextAuthProvider";
import ReactQueryProvider from "@/providers/reactQueryProvider";
import { Provider } from "@/components/ui/provider"

// Fonts setup
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextAuthProvider>
          <ReactQueryProvider>
            <Provider>
              {children}
            </Provider>
          </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
