import React from 'react';
// import React from 'react';
import { Geist, Geist_Mono } from "next/font/google";

// Second - Provider imports


import { Provider } from '@/components/ui/provider';

import ReactQueryProvider from "@/providers/reactQueryProvider";
import NextAuthProvider from '@/providers/nextAuthProvider';

// Last - Global CSS
import "@/style/globals.css";





// Fonts setup
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextAuthProvider>
          <ReactQueryProvider>
            <Provider>
              {children}
            </Provider>
          </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  ); s
}
